# Dependencies
markdown:         kramdown
highlighter:      pygments
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/javicaria/javicaria.github.io/master/images/Logo.png

footer-links:
  email: javiermolinar@live.com
  github: javiermolinar
  linkedin: javiermolinar
  rss: followMe

# Setup
title:            Some Insights
tagline:          'A personal blog'
description:      'Programming stuff'
url:              http://javiermolinar.github.io
baseurl:          /


author:
  name:           'Javier Molina'
paginate:         5

